// <auto-generated />
using E18I4DABH4Gr4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E18I4DABH4Gr4.Migrations
{
    [DbContext(typeof(SmartGridDBContext))]
    partial class SmartGridDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E18I4DABH4Gr4.Models.Prosumer", b =>
                {
                    b.Property<string>("ProsumerId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("ConsumerFK");

                    b.Property<int>("KWhAmount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProducerFK");

                    b.Property<int>("prosumerType");

                    b.HasKey("ProsumerId");

                    b.HasIndex("ConsumerFK");

                    b.HasIndex("ProducerFK");

                    b.ToTable("Prosumers");
                });

            modelBuilder.Entity("E18I4DABH4Gr4.Models.SmartGrid", b =>
                {
                    b.Property<string>("SmartGridId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.HasKey("SmartGridId");

                    b.ToTable("SmartGrids");
                });

            modelBuilder.Entity("E18I4DABH4Gr4.Models.Prosumer", b =>
                {
                    b.HasOne("E18I4DABH4Gr4.Models.SmartGrid")
                        .WithMany("Consumers")
                        .HasForeignKey("ConsumerFK");

                    b.HasOne("E18I4DABH4Gr4.Models.SmartGrid")
                        .WithMany("Producers")
                        .HasForeignKey("ProducerFK");
                });
#pragma warning restore 612, 618
        }
    }
}
